SELECT A.ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPER_INFOS A
    INNER JOIN (SELECT ID 
                FROM DEVELOPER_INFOS
                WHERE CONCAT_WS(', ', SKILL_1, SKILL_2, SKILL_3) LIKE '%Python%') B
    ON A.ID = B.ID
ORDER BY A.ID