SELECT U.*
FROM (SELECT LEFT(ONLS.SALES_DATE,10) SALES_DATE, ONLS.PRODUCT_ID, ONLS.USER_ID, ONLS.SALES_AMOUNT
     FROM ONLINE_SALE ONLS
         UNION ALL
     SELECT LEFT(OFFLS.SALES_DATE,10) SALES_DATE, OFFLS.PRODUCT_ID, null AS USER_ID, OFFLS.SALES_AMOUNT
     FROM OFFLINE_SALE OFFLS) U
WHERE U.SALES_DATE LIKE '2022-03%'
ORDER BY 1, 2, 3