SELECT *
FROM (SELECT CASE 
	WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') 
      		AND SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python')  THEN 'A'
         	WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
            WHEN SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') THEN 'C'
            ELSE null END GRADE, ID, EMAIL
FROM DEVELOPERS) A
WHERE A.GRADE IS NOT null
ORDER BY A.GRADE, A.ID