WITH RECURSIVE HOURS AS(
    SELECT 0 as HOUR
        UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23)

SELECT H.*, COUNT(ANIMAL_ID) COUNT
FROM HOURS H
    LEFT JOIN ANIMAL_OUTS AO
    ON H.HOUR = HOUR(DATETIME)
GROUP BY HOUR