SELECT ROUTE, CONCAT(round(sum(D_BETWEEN_DIST),1),'km') TOTAL_DISTANCE, CONCAT(round(avg(D_BETWEEN_DIST),2),'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY round(sum(D_BETWEEN_DIST),1) DESC