SELECT F.FOOD_TYPE, O.REST_ID, O.REST_NAME, F.FAVORITES
FROM REST_INFO O
    INNER JOIN (SELECT FOOD_TYPE, max(FAVORITES) FAVORITES
                FROM REST_INFO
                GROUP BY FOOD_TYPE
               ) F
    ON O.FOOD_TYPE = F.FOOD_TYPE and O.FAVORITES = F.FAVORITES
ORDER BY O.FOOD_TYPE DESC