SELECT U.USER_ID, U.NICKNAME, CONCAT_WS(' ',U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2) AS 전체주소, CONCAT_WS('-',LEFT(U.TLNO,3),SUBSTR(U.TLNO,4,4),RIGHT(U.TLNO,4)) AS 전화번호
FROM USED_GOODS_BOARD B
    INNER JOIN USED_GOODS_USER U
    ON B.WRITER_ID = U.USER_ID 
GROUP BY B.WRITER_ID HAVING COUNT(B.BOARD_ID) > 2
ORDER BY B.WRITER_ID DESC

# 방법 2
/*
SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ',STREET_ADDRESS1, ' ', STREET_ADDRESS2) 전체주소, REGEXP_REPLACE(TLNO, '(.{3})(.{4})(.{4})', '$1-$2-$3') 전화번호
FROM USED_GOODS_BOARD A
    INNER JOIN USED_GOODS_USER B
    ON A.WRITER_ID = B.USER_ID
GROUP BY USER_ID
HAVING COUNT(USER_ID) > 2
ORDER BY USER_ID DESC
*/