SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(distinct O.USER_ID) USERS
FROM ONLINE_SALE O 
    LEFT JOIN USER_INFO I
    ON O.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL 
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER