SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) as 'count' 
FROM ANIMAL_INS
/*
# 방법1
 WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
*/

# 방법 2
WHERE ANIMAL_TYPE = 'Cat' OR ANIMAL_TYPE = 'Dog'
GROUP BY ANIMAL_TYPE 
ORDER BY ANIMAL_TYPE 