SELECT A.CART_ID
FROM (SELECT CART_ID,  GROUP_CONCAT(distinct NAME SEPARATOR ', ') NAMES
      FROM CART_PRODUCTS
      GROUP BY CART_ID) A
WHERE A.NAMES LIKE '%Milk%' AND A.NAMES LIKE '%Yogurt%'
ORDER BY 1