SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
    INNER JOIN (SELECT ITEM_ID
                FROM ITEM_TREE
                WHERE PARENT_ITEM_ID in (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
                ) T
    ON I.ITEM_ID = T.ITEM_ID
ORDER BY I.ITEM_ID DESC