SELECT month(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE month(START_DATE) BETWEEN 8 AND 10 AND
      CAR_ID IN (SELECT CAR_ID
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE month(START_DATE) BETWEEN 8 AND 10
                 GROUP BY CAR_ID HAVING COUNT(*) > 4 )
GROUP BY MONTH, CAR_ID
ORDER BY 1, 2 DESC