SELECT DISTINCT C.CAR_ID 
FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON C.CAR_ID = RH.CAR_ID
WHERE C.CAR_TYPE = '세단' AND RH.START_DATE LIKE '2022-10-%'
ORDER BY CAR_ID DESC