SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE,'%Y-%m-%d'), 
       CASE WHEN DATEDIFF(LEFT(OUT_DATE,10),'2022-05-01') < 1 THEN '출고완료'
            WHEN DATEDIFF(LEFT(OUT_DATE,10),'2022-05-01') >= 1 THEN '출고대기'
            ELSE '출고미정' END AS 출고여부
FROM FOOD_ORDER
ORDER BY ORDER_ID