SELECT O.CATEGORY, F.MAX_PRICE, O.PRODUCT_NAME
FROM FOOD_PRODUCT O
    INNER JOIN (SELECT CATEGORY, max(PRICE) MAX_PRICE
                FROM FOOD_PRODUCT
                GROUP BY CATEGORY HAVING CATEGORY in ('과자', '국', '김치', '식용유')) F
    ON O.CATEGORY = F.CATEGORY and O.PRICE = F.MAX_PRICE
ORDER BY MAX_PRICE DESC